### ISSUE TITLE
Demo/Showcase Distribution

### ISSUE THREAD

**Issue by doc-rj-ebay** [Anyline/anyline-tiretread-ios-example#8]
Kudos! It's a really nice app to show off the product. Please integrate this scanner into the Anyline Showcase app found in the App Store.

My eBay Motors team would like to evaluate Anyline tire tread scanning for potential inclusion in the eBay Motors app.

However, it's difficult to distribute it to decision makers for demo purposes, unless it's integrated into the App Store.

Thanks!

**Comment by ricardocolombo** [comment]
Hi @doc-rj-ebay, 
sorry for the delay, and thanks for your great feedback! 

Please reach out to our Pre-Sales Consultant Brian Troxell ([Brian.Troxell@anyline.com](mailto:Brian.Troxell@anyline.com)) to discuss the next steps. He can support you with distributing the app to the decision makers.

I will close this issue now, but should you require any further assistance please don't hesitate to contact Brian.

Best regards,
Ricardo
